config/routes.rb
Rails.application.routes.draw do
  resources :clubs
  resources :courses
  resources :holes
  resources :rounds
  resources :shots
  resources :tees

  resources :strokes_expected_putts
  resources :strokes_expected_shots
end

app/models/hole.rb
class Hole < ActiveRecord::Base
end

app/controllers/holes_controller.rb
class HolesController < ApplicationController
  before_action :set_hole, only: [:show, :edit, :update, :destroy]

  # GET /holes
  def index
    @holes = Hole.all
  end

  # GET /holes/1
  def show
  end

  # GET /holes/new
  def new
    @hole = Hole.new
  end

  # GET /holes/1/edit
  def edit
  end

  # POST /holes
  def create
    @hole = Hole.new(hole_params)

    if @hole.save
      redirect_to @hole, notice: 'Hole was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /holes/1
  def update
    if @hole.update(hole_params)
      redirect_to @hole, notice: 'Hole was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /holes/1
  def destroy
    @hole.destroy
    redirect_to holes_url, notice: 'Hole was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hole
      @hole = Hole.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def hole_params
      params[:hole]
    end
end

app/views/holes/_form.html.erb
<%= simple_form_for(@hole) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/holes/edit.html.erb
<h1>Editing Hole</h1>

<%= render 'form' %>

<%= link_to 'Show', @hole %> |
<%= link_to 'Back', holes_path %>

app/views/holes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Holes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @holes.each do |hole| %>
      <tr>
        <td><%= link_to 'Show', hole %></td>
        <td><%= link_to 'Edit', edit_hole_path(hole) %></td>
        <td><%= link_to 'Destroy', hole, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hole', new_hole_path %>

app/views/holes/new.html.erb
<h1>New Hole</h1>

<%= render 'form' %>

<%= link_to 'Back', holes_path %>

app/views/holes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_hole_path(@hole) %> |
<%= link_to 'Back', holes_path %>