config/routes.rb
Rails.application.routes.draw do
  resources :clubs
  resources :courses
  resources :holes
  resources :rounds
  resources :shots
  resources :tees

  resources :strokes_expected_putts
  resources :strokes_expected_shots
end

app/models/tee.rb
class Tee < ActiveRecord::Base
end

app/controllers/tees_controller.rb
class TeesController < ApplicationController
  before_action :set_tee, only: [:show, :edit, :update, :destroy]

  # GET /tees
  def index
    @tees = Tee.all
  end

  # GET /tees/1
  def show
  end

  # GET /tees/new
  def new
    @tee = Tee.new
  end

  # GET /tees/1/edit
  def edit
  end

  # POST /tees
  def create
    @tee = Tee.new(tee_params)

    if @tee.save
      redirect_to @tee, notice: 'Tee was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tees/1
  def update
    if @tee.update(tee_params)
      redirect_to @tee, notice: 'Tee was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tees/1
  def destroy
    @tee.destroy
    redirect_to tees_url, notice: 'Tee was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tee
      @tee = Tee.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def tee_params
      params[:tee]
    end
end

app/views/tees/_form.html.erb
<%= simple_form_for(@tee) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tees/edit.html.erb
<h1>Editing Tee</h1>

<%= render 'form' %>

<%= link_to 'Show', @tee %> |
<%= link_to 'Back', tees_path %>

app/views/tees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tees</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tees.each do |tee| %>
      <tr>
        <td><%= link_to 'Show', tee %></td>
        <td><%= link_to 'Edit', edit_tee_path(tee) %></td>
        <td><%= link_to 'Destroy', tee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tee', new_tee_path %>

app/views/tees/new.html.erb
<h1>New Tee</h1>

<%= render 'form' %>

<%= link_to 'Back', tees_path %>

app/views/tees/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tee_path(@tee) %> |
<%= link_to 'Back', tees_path %>