config/routes.rb
Rails.application.routes.draw do
  resources :clubs
  resources :courses
  resources :holes
  resources :rounds
  resources :shots
  resources :tees

  resources :strokes_expected_putts
  resources :strokes_expected_shots
end

app/models/strokes_expected_putt.rb
class StrokesExpectedPutt < ActiveRecord::Base
end

app/controllers/strokes_expected_putts_controller.rb
class StrokesExpectedPuttsController < ApplicationController
  before_action :set_strokes_expected_putt, only: [:show, :edit, :update, :destroy]

  # GET /strokes_expected_putts
  def index
    @strokes_expected_putts = StrokesExpectedPutt.all
  end

  # GET /strokes_expected_putts/1
  def show
  end

  # GET /strokes_expected_putts/new
  def new
    @strokes_expected_putt = StrokesExpectedPutt.new
  end

  # GET /strokes_expected_putts/1/edit
  def edit
  end

  # POST /strokes_expected_putts
  def create
    @strokes_expected_putt = StrokesExpectedPutt.new(strokes_expected_putt_params)

    if @strokes_expected_putt.save
      redirect_to @strokes_expected_putt, notice: 'Strokes expected putt was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /strokes_expected_putts/1
  def update
    if @strokes_expected_putt.update(strokes_expected_putt_params)
      redirect_to @strokes_expected_putt, notice: 'Strokes expected putt was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /strokes_expected_putts/1
  def destroy
    @strokes_expected_putt.destroy
    redirect_to strokes_expected_putts_url, notice: 'Strokes expected putt was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_strokes_expected_putt
      @strokes_expected_putt = StrokesExpectedPutt.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def strokes_expected_putt_params
      params[:strokes_expected_putt]
    end
end

app/views/strokes_expected_putts/_form.html.erb
<%= simple_form_for(@strokes_expected_putt) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/strokes_expected_putts/edit.html.erb
<h1>Editing Strokes Expected Putt</h1>

<%= render 'form' %>

<%= link_to 'Show', @strokes_expected_putt %> |
<%= link_to 'Back', strokes_expected_putts_path %>

app/views/strokes_expected_putts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Strokes Expected Putts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @strokes_expected_putts.each do |strokes_expected_putt| %>
      <tr>
        <td><%= link_to 'Show', strokes_expected_putt %></td>
        <td><%= link_to 'Edit', edit_strokes_expected_putt_path(strokes_expected_putt) %></td>
        <td><%= link_to 'Destroy', strokes_expected_putt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Strokes expected putt', new_strokes_expected_putt_path %>

app/views/strokes_expected_putts/new.html.erb
<h1>New Strokes Expected Putt</h1>

<%= render 'form' %>

<%= link_to 'Back', strokes_expected_putts_path %>

app/views/strokes_expected_putts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_strokes_expected_putt_path(@strokes_expected_putt) %> |
<%= link_to 'Back', strokes_expected_putts_path %>