config/routes.rb
Rails.application.routes.draw do
  resources :clubs
  resources :courses
  resources :holes
  resources :rounds
  resources :shots
  resources :tees

  resources :strokes_expected_putts
  resources :strokes_expected_shots
end

app/models/strokes_expected_shot.rb
class StrokesExpectedShot < ActiveRecord::Base
end

app/controllers/strokes_expected_shots_controller.rb
class StrokesExpectedShotsController < ApplicationController
  before_action :set_strokes_expected_shot, only: [:show, :edit, :update, :destroy]

  # GET /strokes_expected_shots
  def index
    @strokes_expected_shots = StrokesExpectedShot.all
  end

  # GET /strokes_expected_shots/1
  def show
  end

  # GET /strokes_expected_shots/new
  def new
    @strokes_expected_shot = StrokesExpectedShot.new
  end

  # GET /strokes_expected_shots/1/edit
  def edit
  end

  # POST /strokes_expected_shots
  def create
    @strokes_expected_shot = StrokesExpectedShot.new(strokes_expected_shot_params)

    if @strokes_expected_shot.save
      redirect_to @strokes_expected_shot, notice: 'Strokes expected shot was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /strokes_expected_shots/1
  def update
    if @strokes_expected_shot.update(strokes_expected_shot_params)
      redirect_to @strokes_expected_shot, notice: 'Strokes expected shot was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /strokes_expected_shots/1
  def destroy
    @strokes_expected_shot.destroy
    redirect_to strokes_expected_shots_url, notice: 'Strokes expected shot was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_strokes_expected_shot
      @strokes_expected_shot = StrokesExpectedShot.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def strokes_expected_shot_params
      params[:strokes_expected_shot]
    end
end

app/views/strokes_expected_shots/_form.html.erb
<%= simple_form_for(@strokes_expected_shot) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/strokes_expected_shots/edit.html.erb
<h1>Editing Strokes Expected Shot</h1>

<%= render 'form' %>

<%= link_to 'Show', @strokes_expected_shot %> |
<%= link_to 'Back', strokes_expected_shots_path %>

app/views/strokes_expected_shots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Strokes Expected Shots</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @strokes_expected_shots.each do |strokes_expected_shot| %>
      <tr>
        <td><%= link_to 'Show', strokes_expected_shot %></td>
        <td><%= link_to 'Edit', edit_strokes_expected_shot_path(strokes_expected_shot) %></td>
        <td><%= link_to 'Destroy', strokes_expected_shot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Strokes expected shot', new_strokes_expected_shot_path %>

app/views/strokes_expected_shots/new.html.erb
<h1>New Strokes Expected Shot</h1>

<%= render 'form' %>

<%= link_to 'Back', strokes_expected_shots_path %>

app/views/strokes_expected_shots/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_strokes_expected_shot_path(@strokes_expected_shot) %> |
<%= link_to 'Back', strokes_expected_shots_path %>